# Generated by Django 5.2.1 on 2025-06-06 12:46

import django.core.validators
import django.db.models.deletion
import quiz.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PDFDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quiz_title", models.CharField(max_length=200)),
                (
                    "pdf_file",
                    models.FileField(
                        help_text="Upload PDF file (max 10MB)",
                        upload_to=quiz.models.pdf_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mathematics", "Mathematics"),
                            ("science", "Science"),
                            ("history", "History"),
                            ("literature", "Literature"),
                            ("computer_science", "Computer Science"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("num_questions", models.IntegerField(default=10)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_processed", models.BooleanField(default=False)),
                (
                    "processing_status",
                    models.CharField(default="pending", max_length=50),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "PDF Document",
                "verbose_name_plural": "PDF Documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuestionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("true_false", "True/False"),
                            ("short_answer", "Short Answer"),
                            ("fill_blank", "Fill in the Blank"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "pdf_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_types",
                        to="quiz.pdfdocument",
                    ),
                ),
            ],
            options={
                "unique_together": {("pdf_document", "question_type")},
            },
        ),
    ]
